#!/bin/bash
#set -x

ROOT_UID=0 # Only users with $UID 0 have root privileges.
E_NOTROOT=87 # Non-root exit error.
E_RETRY=1 # Retry exit error
#INSTALLER_DIR=/media/gcca_storage
LIBVIRT_CONFIG_FILE=/etc/libvirt/libvirt.conf
LIBVIRTD_CONFIG_FILE=/etc/libvirt/libvirtd.conf
QEMU_CONFIG_FILE=/etc/libvirt/qemu.conf
NET_CONFIG_FILE=/etc/network/interfaces
RC_LOCAL_FILE=/etc/rc.local
BRIDGE_NAME=br0
INSTALL_USER=gcca
nic1=eth0

echo 'hello'